index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }
productos:
    path: /productos
    defaults: { _controller: 'App\Controller\ProductosController::productos' }
